[package]
name = "brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-format = "0.4.4"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.8.0"
